// ~~ Generated by projen
const { existsSync } = require("fs");
const { execSync } = require("child_process");

function execCommand(command) {
  try {
    execSync(command, { stdio: "inherit" });
  } catch (error) {
    console.error(`Failed to execute command: ${command}`, error);
    process.exit(1);
  }
}

function bootstrap() {
  console.info("bootstrapping...");

  if (!existsSync("node_modules/.bin/jsii")) {
    execCommand(
      "yarn install --frozen-lockfile --check-files --non-interactive"
    );
  }

  execCommand(
    "npx jsii --silence-warnings=reserved-word --no-fix-peer-dependencies"
  );
}

if (!existsSync("lib/cli/index.js")) {
  bootstrap();
}

const args = process.argv.slice(2).join(" ");
execCommand(`bin/projen ${args}`);
