/**
 * Helpers for the `.projen/tasks.json` manifest schema.
 */
export class TasksManifestSchema {
  /**
   * The current version of the tasks manifest schema.
   *
   * Bump this whenever the structure of the manifest changes in a way the task
   * runtime needs to be aware of. The runtime uses it to detect manifests that
   * were produced by a newer (potentially incompatible) version of projen.
   *
   * Manifests generated by older versions of projen do not carry a version at
   * all; those are treated as "legacy" and accepted as-is for backwards
   * compatibility.
   */
  public static readonly VERSION = 1;

  private constructor() {}
}
