import { AwsCdkPythonApp } from "../../src/awscdk";
import { synthSnapshot } from "../util";

test("create cdk python project", () => {
  const p = new AwsCdkPythonApp({
    authorEmail: "test@cdkpythonapp.com",
    authorName: "First Last",
    moduleName: "test_cdk_python_app_project",
    name: "test-cdk-python-app-project",
    version: "0.1.0",
    cdkVersion: "2.8.0",
  });

  const snapshot = synthSnapshot(p);
  expect(Object.keys(snapshot)).toStrictEqual([
    ".gitattributes",
    ".github/workflows/pull-request-lint.yml",
    ".gitignore",
    ".projen/deps.json",
    ".projen/files.json",
    ".projen/tasks.json",
    "app.py",
    "cdk.json",
    "README.md",
    "requirements-dev.txt",
    "requirements.txt",
    "test_cdk_python_app_project/__init__.py",
    "test_cdk_python_app_project/main.py",
    "tests/__init__.py",
    "tests/test_example.py",
  ]);
  expect(snapshot["cdk.json"]).toMatchSnapshot();
});

test("CDK v2 deps", () => {
  const p = new AwsCdkPythonApp({
    authorEmail: "test@cdkpythonapp.com",
    authorName: "First Last",
    moduleName: "test_cdk_python_app_project",
    name: "test-cdk-python-app-project",
    version: "0.1.0",
    cdkVersion: "2.8.0",
  });

  const snapshot = synthSnapshot(p);

  expect(snapshot["requirements.txt"]).toContain(
    '# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".'
  );
  expect(snapshot["requirements.txt"]).toContain("aws-cdk-lib>=2.8.0, <3.0.0");
  expect(snapshot["requirements.txt"]).toContain("constructs>=10.0.5, <11.0.0");

  expect(snapshot["requirements-dev.txt"]).toContain(
    '# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".'
  );
  expect(snapshot["requirements-dev.txt"]).toContain("projen==99.99.99");
});

test("CDK v1 deps", () => {
  const p = new AwsCdkPythonApp({
    authorEmail: "test@cdkpythonapp.com",
    authorName: "First Last",
    moduleName: "test_cdk_python_app_project",
    name: "test-cdk-python-app-project",
    version: "0.1.0",
    cdkVersion: "1.140.0",
  });

  const snapshot = synthSnapshot(p);

  expect(snapshot["requirements.txt"]).toContain(
    '# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".'
  );
  expect(snapshot["requirements.txt"]).toContain(
    "aws_cdk.core>=1.140.0, <2.0.0"
  );
  expect(snapshot["requirements.txt"]).toContain("constructs>=3.2.27, <4.0.0");

  expect(snapshot["requirements-dev.txt"]).toContain(
    '# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".'
  );
  expect(snapshot["requirements-dev.txt"]).toContain("projen==99.99.99");
});
