// ~~ Generated by projen. To modify, edit .projenrc.ts and run "node ./projen.js".
/**
 * @schema PdmConfiguration
 */
export interface PdmConfiguration {
  /**
   * Whether the project needs to be distributed
   *
   * @schema PdmConfiguration#distribution
   */
  readonly distribution?: boolean;

  /**
   * Ignore package resolution warnings for packages matching the given patterns (PDM v2.10.0)
   *
   * @schema PdmConfiguration#ignore_package_warnings
   */
  readonly ignorePackageWarnings?: string[];

  /**
   * Development dependencies
   *
   * @schema PdmConfiguration#dev-dependencies
   */
  readonly devDependencies?: PdmConfigurationDevDependencies;

  /**
   * Configuration related to package resolution
   *
   * @schema PdmConfiguration#resolution
   */
  readonly resolution?: PdmConfigurationResolution;

  /**
   * Default options applied to a PDM command
   *
   * @schema PdmConfiguration#options
   */
  readonly options?: PdmConfigurationOptions;

  /**
   * List of PDM plugins required for this project
   *
   * @schema PdmConfiguration#plugins
   */
  readonly plugins?: string[];

  /**
   * Sources used for package resolution
   *
   * @schema PdmConfiguration#source
   */
  readonly source?: PackageSource[];

  /**
   * Definition of PDM scripts
   *
   * @schema PdmConfiguration#scripts
   */
  readonly scripts?: PdmConfigurationScripts;

  /**
   * Dynamic version options for PDM-backend
   *
   * @schema PdmConfiguration#version
   */
  readonly version?: PdmConfigurationVersion;

  /**
   * Configuration related to the build process with pdm-backend
   *
   * @schema PdmConfiguration#buildConfig
   */
  readonly buildConfig?: PdmConfigurationBuild;

  /**
   * PDM Dockerize plugin table in pyproject.toml
   *
   * @schema PdmConfiguration#dockerize
   */
  readonly dockerize?: PdmConfigurationDockerize;
}

/**
 * Converts an object of type 'PdmConfiguration' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfiguration(obj: PdmConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'distribution': obj.distribution,
    'ignore_package_warnings': obj.ignorePackageWarnings?.map(y => y),
    'dev-dependencies': toJson_PdmConfigurationDevDependencies(obj.devDependencies),
    'resolution': toJson_PdmConfigurationResolution(obj.resolution),
    'options': toJson_PdmConfigurationOptions(obj.options),
    'plugins': obj.plugins?.map(y => y),
    'source': obj.source?.map(y => toJson_PackageSource(y)),
    'scripts': toJson_PdmConfigurationScripts(obj.scripts),
    'version': toJson_PdmConfigurationVersion(obj.version),
    'build': toJson_PdmConfigurationBuild(obj.buildConfig),
    'dockerize': toJson_PdmConfigurationDockerize(obj.dockerize),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Development dependencies
 *
 * @schema PdmConfigurationDevDependencies
 */
export interface PdmConfigurationDevDependencies {
  /**
   * The default dev dependencies
   *
   * @schema PdmConfigurationDevDependencies#dev
   */
  readonly dev?: string[];
}

/**
 * Converts an object of type 'PdmConfigurationDevDependencies' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationDevDependencies(obj: PdmConfigurationDevDependencies | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'dev': obj.dev?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration related to package resolution
 *
 * @schema PdmConfigurationResolution
 */
export interface PdmConfigurationResolution {
  /**
   * Whether to allow the use of pre-releases when resolving packages
   *
   * @schema PdmConfigurationResolution#allow-prereleases
   */
  readonly allowPrereleases?: boolean;

  /**
   * Package names to be excluded from the resolution result
   *
   * @schema PdmConfigurationResolution#excludes
   */
  readonly excludes?: string[];

  /**
   * Whether PDM prefers package sources by order
   *
   * @schema PdmConfigurationResolution#respect-source-order
   */
  readonly respectSourceOrder?: boolean;

  /**
   * Resolution overrides for forcing specific dependency versions
   *
   * @schema PdmConfigurationResolution#overrides
   */
  readonly overrides?: { [key: string]: string };
}

/**
 * Converts an object of type 'PdmConfigurationResolution' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationResolution(obj: PdmConfigurationResolution | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'allow-prereleases': obj.allowPrereleases,
    'excludes': obj.excludes?.map(y => y),
    'respect-source-order': obj.respectSourceOrder,
    'overrides': ((obj.overrides) === undefined) ? undefined : (Object.entries(obj.overrides).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Default options applied to a PDM command
 *
 * @schema PdmConfigurationOptions
 */
export interface PdmConfigurationOptions {
  /**
   * @schema PdmConfigurationOptions#add
   */
  readonly add?: string[];

  /**
   * @schema PdmConfigurationOptions#buildConfig
   */
  readonly buildConfig?: string[];

  /**
   * @schema PdmConfigurationOptions#cache
   */
  readonly cache?: string[];

  /**
   * @schema PdmConfigurationOptions#completion
   */
  readonly completion?: string[];

  /**
   * @schema PdmConfigurationOptions#config
   */
  readonly config?: string[];

  /**
   * @schema PdmConfigurationOptions#export
   */
  readonly export?: string[];

  /**
   * @schema PdmConfigurationOptions#fix
   */
  readonly fix?: string[];

  /**
   * @schema PdmConfigurationOptions#import
   */
  readonly import?: string[];

  /**
   * @schema PdmConfigurationOptions#info
   */
  readonly info?: string[];

  /**
   * @schema PdmConfigurationOptions#init
   */
  readonly init?: string[];

  /**
   * @schema PdmConfigurationOptions#install
   */
  readonly install?: string[];

  /**
   * @schema PdmConfigurationOptions#list
   */
  readonly list?: string[];

  /**
   * @schema PdmConfigurationOptions#lock
   */
  readonly lock?: string[];

  /**
   * @schema PdmConfigurationOptions#publish
   */
  readonly publish?: string[];

  /**
   * @schema PdmConfigurationOptions#remove
   */
  readonly remove?: string[];

  /**
   * @schema PdmConfigurationOptions#run
   */
  readonly run?: string[];

  /**
   * @schema PdmConfigurationOptions#search
   */
  readonly search?: string[];

  /**
   * @schema PdmConfigurationOptions#self
   */
  readonly self?: string[];

  /**
   * @schema PdmConfigurationOptions#show
   */
  readonly show?: string[];

  /**
   * @schema PdmConfigurationOptions#sync
   */
  readonly sync?: string[];

  /**
   * @schema PdmConfigurationOptions#update
   */
  readonly update?: string[];

  /**
   * @schema PdmConfigurationOptions#use
   */
  readonly use?: string[];

  /**
   * @schema PdmConfigurationOptions#venv
   */
  readonly venv?: string[];
}

/**
 * Converts an object of type 'PdmConfigurationOptions' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationOptions(obj: PdmConfigurationOptions | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'add': obj.add?.map(y => y),
    'build': obj.buildConfig?.map(y => y),
    'cache': obj.cache?.map(y => y),
    'completion': obj.completion?.map(y => y),
    'config': obj.config?.map(y => y),
    'export': obj.export?.map(y => y),
    'fix': obj.fix?.map(y => y),
    'import': obj.import?.map(y => y),
    'info': obj.info?.map(y => y),
    'init': obj.init?.map(y => y),
    'install': obj.install?.map(y => y),
    'list': obj.list?.map(y => y),
    'lock': obj.lock?.map(y => y),
    'publish': obj.publish?.map(y => y),
    'remove': obj.remove?.map(y => y),
    'run': obj.run?.map(y => y),
    'search': obj.search?.map(y => y),
    'self': obj.self?.map(y => y),
    'show': obj.show?.map(y => y),
    'sync': obj.sync?.map(y => y),
    'update': obj.update?.map(y => y),
    'use': obj.use?.map(y => y),
    'venv': obj.venv?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Package source
 *
 * @schema package-source
 */
export interface PackageSource {
  /**
   * Name of the package source
   *
   * @schema package-source#name
   */
  readonly name: string;

  /**
   * HTTP url for the package source
   *
   * @schema package-source#url
   */
  readonly url: string;

  /**
   * Whether to verify certificates when using the package source
   *
   * @schema package-source#verify_ssl
   */
  readonly verifySsl?: boolean;

  /**
   * Username for the package source
   *
   * @schema package-source#username
   */
  readonly username?: string;

  /**
   * Password for the package source
   *
   * @schema package-source#password
   */
  readonly password?: string;

  /**
   * index or find_links
   *
   * @schema package-source#type
   */
  readonly type?: PackageSourceType;

  /**
   * Glob patterns of packages that should not be used from this source. Ignored if include_packages configuration is present
   *
   * @schema package-source#exclude_packages
   */
  readonly excludePackages?: string[];

  /**
   * Glob patterns of the only packages that should be used from this source
   *
   * @schema package-source#include_packages
   */
  readonly includePackages?: string[];
}

/**
 * Converts an object of type 'PackageSource' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PackageSource(obj: PackageSource | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'url': obj.url,
    'verify_ssl': obj.verifySsl,
    'username': obj.username,
    'password': obj.password,
    'type': obj.type,
    'exclude_packages': obj.excludePackages?.map(y => y),
    'include_packages': obj.includePackages?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Definition of PDM scripts
 *
 * @schema PdmConfigurationScripts
 */
export interface PdmConfigurationScripts {
  /**
   * @schema PdmConfigurationScripts#post_init
   */
  readonly postInit?: any;

  /**
   * @schema PdmConfigurationScripts#pre_install
   */
  readonly preInstall?: any;

  /**
   * @schema PdmConfigurationScripts#post_install
   */
  readonly postInstall?: any;

  /**
   * @schema PdmConfigurationScripts#pre_lock
   */
  readonly preLock?: any;

  /**
   * @schema PdmConfigurationScripts#post_lock
   */
  readonly postLock?: any;

  /**
   * @schema PdmConfigurationScripts#pre_build
   */
  readonly preBuild?: any;

  /**
   * @schema PdmConfigurationScripts#post_build
   */
  readonly postBuild?: any;

  /**
   * @schema PdmConfigurationScripts#pre_publish
   */
  readonly prePublish?: any;

  /**
   * @schema PdmConfigurationScripts#post_publish
   */
  readonly postPublish?: any;

  /**
   * @schema PdmConfigurationScripts#pre_script
   */
  readonly preScript?: any;

  /**
   * @schema PdmConfigurationScripts#post_script
   */
  readonly postScript?: any;

  /**
   * @schema PdmConfigurationScripts#pre_run
   */
  readonly preRun?: any;

  /**
   * @schema PdmConfigurationScripts#post_run
   */
  readonly postRun?: any;
}

/**
 * Converts an object of type 'PdmConfigurationScripts' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationScripts(obj: PdmConfigurationScripts | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'post_init': obj.postInit,
    'pre_install': obj.preInstall,
    'post_install': obj.postInstall,
    'pre_lock': obj.preLock,
    'post_lock': obj.postLock,
    'pre_build': obj.preBuild,
    'post_build': obj.postBuild,
    'pre_publish': obj.prePublish,
    'post_publish': obj.postPublish,
    'pre_script': obj.preScript,
    'post_script': obj.postScript,
    'pre_run': obj.preRun,
    'post_run': obj.postRun,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Dynamic version options for PDM-backend
 *
 * @schema PdmConfigurationVersion
 */
export interface PdmConfigurationVersion {
  /**
   * Dynamic version source
   *
   * @schema PdmConfigurationVersion#source
   */
  readonly source: PdmConfigurationVersionSource;

  /**
   * Path to python file to read version from (file source)
   *
   * @schema PdmConfigurationVersion#path
   */
  readonly path?: string;

  /**
   * Specify a default version to be used when building from a source tree where SCM is not available (since pdm-backend v2.2.0)
   *
   * @schema PdmConfigurationVersion#fallback_version
   */
  readonly fallbackVersion?: string;

  /**
   * Filters the set of tags which are considered as candidates to capture your project's version (scm source)
   *
   * @schema PdmConfigurationVersion#tag_filter
   */
  readonly tagFilter?: string;

  /**
   * Regex for reading version from source control tag (scm source)
   *
   * @schema PdmConfigurationVersion#tag_regex
   */
  readonly tagRegex?: string;

  /**
   * Used to customize the format of the version string (since pdm-backend v2.2.0)
   *
   * @schema PdmConfigurationVersion#version_format
   */
  readonly versionFormat?: string;

  /**
   * Python callable for reading version
   *
   * @schema PdmConfigurationVersion#getter
   */
  readonly getter?: string;

  /**
   * File path a generated version should be written to
   *
   * @schema PdmConfigurationVersion#write_to
   */
  readonly writeTo?: string;

  /**
   * Template to use for generated version file
   *
   * @schema PdmConfigurationVersion#write_template
   */
  readonly writeTemplate?: string;
}

/**
 * Converts an object of type 'PdmConfigurationVersion' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationVersion(obj: PdmConfigurationVersion | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'source': obj.source,
    'path': obj.path,
    'fallback_version': obj.fallbackVersion,
    'tag_filter': obj.tagFilter,
    'tag_regex': obj.tagRegex,
    'version_format': obj.versionFormat,
    'getter': obj.getter,
    'write_to': obj.writeTo,
    'write_template': obj.writeTemplate,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration related to the build process with pdm-backend
 *
 * @schema PdmConfigurationBuild
 */
export interface PdmConfigurationBuild {
  /**
   * Path patterns of files to be included in the package
   *
   * @schema PdmConfigurationBuild#includes
   */
  readonly includes?: string[];

  /**
   * Path patterns of files to be excluded from package
   *
   * @schema PdmConfigurationBuild#excludes
   */
  readonly excludes?: string[];

  /**
   * Path patterns of files that are needed for building but not meant to be copied to the site-packages directory
   *
   * @schema PdmConfigurationBuild#source-includes
   */
  readonly sourceIncludes?: string[];

  /**
   * Directory where packages are located. The default value is src if src/ is found and . otherwise
   *
   * @schema PdmConfigurationBuild#package-dir
   */
  readonly packageDir?: string;

  /**
   * Python file that should be run before every build
   *
   * @schema PdmConfigurationBuild#custom-hook
   */
  readonly customHook?: string;

  /**
   * Whether to auto-generate setup.py and run setuptools with it. Useful for building C extensions
   *
   * @schema PdmConfigurationBuild#run-setuptools
   */
  readonly runSetuptools?: boolean;

  /**
   * Whether builds should be platform specific
   *
   * @schema PdmConfigurationBuild#is-purelib
   */
  readonly isPurelib?: boolean;

  /**
   * Format of editable wheels
   *
   * @schema PdmConfigurationBuild#editable-backend
   */
  readonly editableBackend?: PdmConfigurationBuildEditableBackend;

  /**
   * Configuration for additional files to be written to a user's site-packages directory
   *
   * @schema PdmConfigurationBuild#wheel-data
   */
  readonly wheelData?: PdmConfigurationBuildWheelData;
}

/**
 * Converts an object of type 'PdmConfigurationBuild' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationBuild(obj: PdmConfigurationBuild | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'includes': obj.includes?.map(y => y),
    'excludes': obj.excludes?.map(y => y),
    'source-includes': obj.sourceIncludes?.map(y => y),
    'package-dir': obj.packageDir,
    'custom-hook': obj.customHook,
    'run-setuptools': obj.runSetuptools,
    'is-purelib': obj.isPurelib,
    'editable-backend': obj.editableBackend,
    'wheel-data': toJson_PdmConfigurationBuildWheelData(obj.wheelData),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * PDM Dockerize plugin table in pyproject.toml
 *
 * @schema PdmConfigurationDockerize
 */
export interface PdmConfigurationDockerize {
  /**
   * fnmatch filter patterns for included PDM scripts
   *
   * @schema PdmConfigurationDockerize#include
   */
  readonly include?: string[];

  /**
   * fnmatch filter patterns for excluded PDM scripts
   *
   * @schema PdmConfigurationDockerize#exclude
   */
  readonly exclude?: string[];

  /**
   * fnmatch filter patterns for included binaries
   *
   * @schema PdmConfigurationDockerize#include_bins
   */
  readonly includeBins?: string[];

  /**
   * fnmatch filter patterns for excluded binaries
   *
   * @schema PdmConfigurationDockerize#exclude_bins
   */
  readonly excludeBins?: string[];

  /**
   * Path to a file with environment variables
   *
   * @schema PdmConfigurationDockerize#env_file
   */
  readonly envFile?: string;

  /**
   * Environment variables applied when running the script
   *
   * @schema PdmConfigurationDockerize#env
   */
  readonly env?: { [key: string]: string };
}

/**
 * Converts an object of type 'PdmConfigurationDockerize' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationDockerize(obj: PdmConfigurationDockerize | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'include': obj.include?.map(y => y),
    'exclude': obj.exclude?.map(y => y),
    'include_bins': obj.includeBins?.map(y => y),
    'exclude_bins': obj.excludeBins?.map(y => y),
    'env_file': obj.envFile,
    'env': ((obj.env) === undefined) ? undefined : (Object.entries(obj.env).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * index or find_links
 *
 * @schema PackageSourceType
 */
export enum PackageSourceType {
  /** index */
  INDEX = "index",
  /** find_links */
  FIND_UNDERSCORE_LINKS = "find_links",
}

/**
 * Shared options for all scripts
 * https://pdm-project.org/latest/usage/scripts/#shared-options
 *
 * @schema PdmConfigurationScriptsEnv
 */
export interface PdmConfigurationScriptsEnv {
  /**
   * @schema PdmConfigurationScriptsEnv#env
   */
  readonly env?: { [key: string]: string };

  /**
   * @schema PdmConfigurationScriptsEnv#env_file
   */
  readonly envFile?: any;
}

/**
 * Converts an object of type 'PdmConfigurationScriptsEnv' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationScriptsEnv(obj: PdmConfigurationScriptsEnv | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'env': ((obj.env) === undefined) ? undefined : (Object.entries(obj.env).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'env_file': obj.envFile,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Dynamic version source
 *
 * @schema PdmConfigurationVersionSource
 */
export enum PdmConfigurationVersionSource {
  /** file */
  FILE = "file",
  /** scm */
  SCM = "scm",
  /** call */
  CALL = "call",
}

/**
 * Format of editable wheels
 *
 * @schema PdmConfigurationBuildEditableBackend
 */
export enum PdmConfigurationBuildEditableBackend {
  /** path */
  PATH = "path",
  /** editables */
  EDITABLES = "editables",
}

/**
 * Configuration for additional files to be written to a user's site-packages directory
 *
 * @schema PdmConfigurationBuildWheelData
 */
export interface PdmConfigurationBuildWheelData {
  /**
   * @schema PdmConfigurationBuildWheelData#scripts
   */
  readonly scripts?: any[];

  /**
   * @schema PdmConfigurationBuildWheelData#purelib
   */
  readonly purelib?: any[];

  /**
   * @schema PdmConfigurationBuildWheelData#platlib
   */
  readonly platlib?: any[];

  /**
   * @schema PdmConfigurationBuildWheelData#include
   */
  readonly include?: any[];

  /**
   * @schema PdmConfigurationBuildWheelData#platinclude
   */
  readonly platinclude?: any[];

  /**
   * @schema PdmConfigurationBuildWheelData#data
   */
  readonly data?: any[];
}

/**
 * Converts an object of type 'PdmConfigurationBuildWheelData' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PdmConfigurationBuildWheelData(obj: PdmConfigurationBuildWheelData | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'scripts': obj.scripts?.map(y => y),
    'purelib': obj.purelib?.map(y => y),
    'platlib': obj.platlib?.map(y => y),
    'include': obj.include?.map(y => y),
    'platinclude': obj.platinclude?.map(y => y),
    'data': obj.data?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
