// ~~ Generated by projen. To modify, edit .projenrc.ts and run "node ./projen.js".
/**
 * JSON schema for pytest configuration options under `[tool.pytest]` in `pyproject.toml`.
 *
 * @schema PytestConfiguration
 */
export interface PytestConfiguration {
  /**
   * Add the specified OPTS to the set of command line arguments as if they had been specified by the user.
   *
   * @schema PytestConfiguration#addopts
   */
  readonly addopts?: string[];

  /**
   * Sets the directory where the cache plugin’s content is stored.
   *
   * @schema PytestConfiguration#cache_dir
   */
  readonly cacheDir?: string;

  /**
   * Settings this to false will make pytest collect classes/functions from test files _only_ if they are defined in that file (as opposed to imported there).
   *
   * @schema PytestConfiguration#collect_imported_tests
   */
  readonly collectImportedTests?: boolean;

  /**
   * Controls if pytest should attempt to identify namespace packages when collecting Python modules.
   *
   * @schema PytestConfiguration#consider_namespace_packages
   */
  readonly considerNamespacePackages?: boolean;

  /**
   * Sets console output style during test execution.
   *
   * @schema PytestConfiguration#console_output_style
   */
  readonly consoleOutputStyle?: PytestConfigurationConsoleOutputStyle;

  /**
   * pytest by default escapes any non-ascii characters used in unicode strings for the parametrization because it has several downsides. If however you would like to use unicode strings in parametrization and see them in the terminal as is (non-escaped), use this option in your configuration file
   *
   * @schema PytestConfiguration#disable_test_id_escaping_and_forfeit_all_rights_to_community_support
   */
  readonly disableTestIdEscapingAndForfeitAllRightsToCommunitySupport?: boolean;

  /**
   * Default encoding to use to decode text files with docstrings.
   *
   * @schema PytestConfiguration#doctest_encoding
   */
  readonly doctestEncoding?: string;

  /**
   * One or more doctest flag names from the standard doctest module.
   *
   * @schema PytestConfiguration#doctest_optionflags
   */
  readonly doctestOptionflags?: string[];

  /**
   * Allows to pick the action for empty parametersets in parameterization.
   *
   * @schema PytestConfiguration#empty_parameter_set_mark
   */
  readonly emptyParameterSetMark?: PytestConfigurationEmptyParameterSetMark;

  /**
   * Enables the pytest_assertion_pass hook. Make sure to delete any previously generated .pyc cache files.
   *
   * @schema PytestConfiguration#enable_assertion_pass_hook
   */
  readonly enableAssertionPassHook?: boolean;

  /**
   * Exit the pytest process after the per-test timeout is reached by passing exit=True to the faulthandler.dump_traceback_later() function. This is particularly useful to avoid wasting CI resources for test suites that are prone to putting the main Python interpreter into a deadlock state.
   *
   * @schema PytestConfiguration#faulthandler_exit_on_timeout
   */
  readonly faulthandlerExitOnTimeout?: boolean;

  /**
   * Dumps the tracebacks of all threads if a test takes longer than X seconds to run (including fixture setup and teardown). Implemented using the faulthandler.dump_traceback_later() function, so all caveats there apply.
   *
   * @schema PytestConfiguration#faulthandler_timeout
   */
  readonly faulthandlerTimeout?: number;

  /**
   * Sets a list of filters and actions that should be taken for matched warnings. By default all warnings emitted during the test session will be displayed in a summary at the end of the test session.
   *
   * @schema PytestConfiguration#filterwarnings
   */
  readonly filterwarnings?: string[];

  /**
   * Configures how durations are recorded into the JUnit XML report:
   *
   * @schema PytestConfiguration#junit_duration_report
   */
  readonly junitDurationReport?: PytestConfigurationJunitDurationReport;

  /**
   * Configures the format of the generated JUnit XML file.
   *
   * @schema PytestConfiguration#junit_family
   */
  readonly junitFamily?: PytestConfigurationJunitFamily;

  /**
   * If junit_logging is enabled, configures if the captured output should be written to the JUnit XML file for passing tests.
   *
   * @schema PytestConfiguration#junit_log_passing_tests
   */
  readonly junitLogPassingTests?: boolean;

  /**
   * Configures if captured output should be written to the JUnit XML file.
   *
   * @schema PytestConfiguration#junit_logging
   */
  readonly junitLogging?: PytestConfigurationJunitLogging;

  /**
   * To set the name of the root test suite xml item, you can configure the junit_suite_name option in your config file.
   *
   * @schema PytestConfiguration#junit_suite_name
   */
  readonly junitSuiteName?: string;

  /**
   * Allow selective auto-indentation of multiline log messages.
   *
   * @schema PytestConfiguration#log_auto_indent
   */
  readonly logAutoIndent?: PytestConfigurationLogAutoIndent;

  /**
   * Enable log display during test run (also known as “live logging”).
   *
   * @schema PytestConfiguration#log_cli
   */
  readonly logCli?: boolean;

  /**
   * Sets a time.strftime()-compatible string that will be used when formatting dates for live logging.
   *
   * @schema PytestConfiguration#log_cli_date_format
   */
  readonly logCliDateFormat?: string;

  /**
   * Sets a logging-compatible string used to format live logging messages.
   *
   * @schema PytestConfiguration#log_cli_format
   */
  readonly logCliFormat?: string;

  /**
   * Sets the minimum log message level that should be captured for live logging. The integer value or the names of the levels can be used.
   *
   * @schema PytestConfiguration#log_cli_level
   */
  readonly logCliLevel?: LogLevel;

  /**
   * Sets a time.strftime()-compatible string that will be used when formatting dates for logging capture.
   *
   * @schema PytestConfiguration#log_date_format
   */
  readonly logDateFormat?: string;

  /**
   * Sets a file name relative to the current working directory where log messages should be written to, in addition to the other logging facilities that are active.
   *
   * @schema PytestConfiguration#log_file
   */
  readonly logFile?: string;

  /**
   * Sets a time.strftime()-compatible string that will be used when formatting dates for the logging file.
   *
   * @schema PytestConfiguration#log_file_date_format
   */
  readonly logFileDateFormat?: string;

  /**
   * Sets a logging-compatible string used to format logging messages redirected to the logging file.
   *
   * @schema PytestConfiguration#log_file_format
   */
  readonly logFileFormat?: string;

  /**
   * Sets the minimum log message level that should be captured for the logging file. The integer value or the names of the levels can be used.
   *
   * @schema PytestConfiguration#log_file_level
   */
  readonly logFileLevel?: LogLevel;

  /**
   * Sets the mode that the logging file is opened with. The options are 'w' to recreate the file (the default) or 'a' to append to the file.
   *
   * @schema PytestConfiguration#log_file_mode
   */
  readonly logFileMode?: PytestConfigurationLogFileMode;

  /**
   * Sets a logging-compatible string used to format captured logging messages.
   *
   * @schema PytestConfiguration#log_format
   */
  readonly logFormat?: string;

  /**
   * Sets the minimum log message level that should be captured for logging capture. The integer value or the names of the levels can be used.
   *
   * @schema PytestConfiguration#log_level
   */
  readonly logLevel?: LogLevel;

  /**
   * When the strict_markers configuration option is set, only known markers - defined in code by core pytest or some plugin - are allowed. You can list additional markers in this setting to add them to the whitelist, in which case you probably want to set strict_markers to true to avoid future regressions.
   *
   * @schema PytestConfiguration#markers
   */
  readonly markers?: string[];

  /**
   * Specifies a minimal pytest version required for running tests.
   *
   * @schema PytestConfiguration#minversion
   */
  readonly minversion?: string;

  /**
   * Set the directory basename patterns to avoid when recursing for test discovery. The individual (fnmatch-style) patterns are applied to the basename of a directory to decide if to recurse into it.
   *
   * @schema PytestConfiguration#norecursedirs
   */
  readonly norecursedirs?: string[];

  /**
   * One or more name prefixes or glob-style patterns determining which classes are considered for test collection. Search for multiple glob patterns by adding a space between patterns. By default, pytest will consider any class prefixed with Test as a test collection.
   *
   * @schema PytestConfiguration#python_classes
   */
  readonly pythonClasses?: string[];

  /**
   * One or more Glob-style file patterns determining which python files are considered as test modules.
   *
   * @schema PytestConfiguration#python_files
   */
  readonly pythonFiles?: string[];

  /**
   * One or more name prefixes or glob-patterns determining which test functions and methods are considered tests. Search for multiple glob patterns by adding a space between patterns. By default, pytest will consider any function prefixed with test as a test.
   *
   * @schema PytestConfiguration#python_functions
   */
  readonly pythonFunctions?: string[];

  /**
   * Sets list of directories that should be added to the python search path. Directories will be added to the head of sys.path. Similar to the PYTHONPATH environment variable, the directories will be included in where Python will look for imported modules. Paths are relative to the rootdir directory.
   *
   * @schema PytestConfiguration#pythonpath
   */
  readonly pythonpath?: string[];

  /**
   * A list of plugins that must be present for pytest to run. Plugins can be listed with or without version specifiers directly following their name.
   *
   * @schema PytestConfiguration#required_plugins
   */
  readonly requiredPlugins?: string[];

  /**
   * If set to true, enable 'strict mode', which enables a number of other strict options.
   *
   * @schema PytestConfiguration#strict
   */
  readonly strict?: boolean;

  /**
   * If set to true, any warnings encountered while parsing the pytest section of the configuration file will raise errors.
   *
   * @schema PytestConfiguration#strict_config
   */
  readonly strictConfig?: boolean;

  /**
   * If set to true, markers not registered in the markers section of the configuration file will raise errors.
   *
   * @schema PytestConfiguration#strict_markers
   */
  readonly strictMarkers?: boolean;

  /**
   * If set to true, pytest emits an error if it detects non-unique parameter set IDs. If not set (the default), pytest automatically handles this by adding 0, 1, … to duplicate IDs, making them unique.
   *
   * @schema PytestConfiguration#strict_parametrization_ids
   */
  readonly strictParametrizationIds?: boolean;

  /**
   * If set to true, tests marked with @pytest.mark.xfail that actually succeed will by default fail the test suite.
   *
   * @schema PytestConfiguration#strict_xfail
   */
  readonly strictXfail?: boolean;

  /**
   * Sets list of directories that should be searched for tests when no specific directories, files or test ids are given in the command line when executing pytest from the rootdir directory. File system paths may use shell-style wildcards, including the recursive ** pattern. Useful when all project tests are in a known location to speed up test collection and to avoid picking up undesired tests by accident.
   *
   * @schema PytestConfiguration#testpaths
   */
  readonly testpaths?: string[];

  /**
   * How many sessions should we keep the tmp_path directories, according to tmp_path_retention_policy.
   *
   * @schema PytestConfiguration#tmp_path_retention_count
   */
  readonly tmpPathRetentionCount?: number;

  /**
   * Controls which directories created by the tmp_path fixture are kept around, based on test outcome.
   *
   * @schema PytestConfiguration#tmp_path_retention_policy
   */
  readonly tmpPathRetentionPolicy?: PytestConfigurationTmpPathRetentionPolicy;

  /**
   * Controls maximum number of characters to truncate assertion message contents. Setting value to 0 disables the character limit for truncation.
   *
   * @schema PytestConfiguration#truncation_limit_chars
   */
  readonly truncationLimitChars?: number;

  /**
   * Controls maximum number of linesto truncate assertion message contents. Setting value to 0 disables the lines limit for truncation.
   *
   * @schema PytestConfiguration#truncation_limit_lines
   */
  readonly truncationLimitLines?: number;

  /**
   * List of fixtures that will be applied to all test functions; this is semantically the same to apply the @pytest.mark.usefixtures marker to all test functions.
   *
   * @schema PytestConfiguration#usefixtures
   */
  readonly usefixtures?: string[];

  /**
   * Set a verbosity level specifically for assertion related output, overriding the application wide level.
   *
   * @schema PytestConfiguration#verbosity_assertions
   */
  readonly verbosityAssertions?: PytestConfigurationVerbosityAssertions;

  /**
   * Set the verbosity level specifically for passed subtests. A value of 1 or higher will show output for passed subtests (failed subtests are always reported). Passed subtests output can be suppressed with the value 0, which overwrites the -v command-line option.
   *
   * @schema PytestConfiguration#verbosity_subtests
   */
  readonly verbositySubtests?: PytestConfigurationVerbositySubtests;

  /**
   * Set a verbosity level specifically for test case execution related output, overriding the application wide level.
   *
   * @schema PytestConfiguration#verbosity_test_cases
   */
  readonly verbosityTestCases?: PytestConfigurationVerbosityTestCases;
}

/**
 * Converts an object of type 'PytestConfiguration' to JSON representation.
 * @internal
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_PytestConfiguration(obj: PytestConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'addopts': obj.addopts?.map(y => y),
    'cache_dir': obj.cacheDir,
    'collect_imported_tests': obj.collectImportedTests,
    'consider_namespace_packages': obj.considerNamespacePackages,
    'console_output_style': obj.consoleOutputStyle,
    'disable_test_id_escaping_and_forfeit_all_rights_to_community_support': obj.disableTestIdEscapingAndForfeitAllRightsToCommunitySupport,
    'doctest_encoding': obj.doctestEncoding,
    'doctest_optionflags': obj.doctestOptionflags?.map(y => y),
    'empty_parameter_set_mark': obj.emptyParameterSetMark,
    'enable_assertion_pass_hook': obj.enableAssertionPassHook,
    'faulthandler_exit_on_timeout': obj.faulthandlerExitOnTimeout,
    'faulthandler_timeout': obj.faulthandlerTimeout,
    'filterwarnings': obj.filterwarnings?.map(y => y),
    'junit_duration_report': obj.junitDurationReport,
    'junit_family': obj.junitFamily,
    'junit_log_passing_tests': obj.junitLogPassingTests,
    'junit_logging': obj.junitLogging,
    'junit_suite_name': obj.junitSuiteName,
    'log_auto_indent': obj.logAutoIndent?.value,
    'log_cli': obj.logCli,
    'log_cli_date_format': obj.logCliDateFormat,
    'log_cli_format': obj.logCliFormat,
    'log_cli_level': obj.logCliLevel,
    'log_date_format': obj.logDateFormat,
    'log_file': obj.logFile,
    'log_file_date_format': obj.logFileDateFormat,
    'log_file_format': obj.logFileFormat,
    'log_file_level': obj.logFileLevel,
    'log_file_mode': obj.logFileMode,
    'log_format': obj.logFormat,
    'log_level': obj.logLevel,
    'markers': obj.markers?.map(y => y),
    'minversion': obj.minversion,
    'norecursedirs': obj.norecursedirs?.map(y => y),
    'python_classes': obj.pythonClasses?.map(y => y),
    'python_files': obj.pythonFiles?.map(y => y),
    'python_functions': obj.pythonFunctions?.map(y => y),
    'pythonpath': obj.pythonpath?.map(y => y),
    'required_plugins': obj.requiredPlugins?.map(y => y),
    'strict': obj.strict,
    'strict_config': obj.strictConfig,
    'strict_markers': obj.strictMarkers,
    'strict_parametrization_ids': obj.strictParametrizationIds,
    'strict_xfail': obj.strictXfail,
    'testpaths': obj.testpaths?.map(y => y),
    'tmp_path_retention_count': obj.tmpPathRetentionCount,
    'tmp_path_retention_policy': obj.tmpPathRetentionPolicy,
    'truncation_limit_chars': obj.truncationLimitChars,
    'truncation_limit_lines': obj.truncationLimitLines,
    'usefixtures': obj.usefixtures?.map(y => y),
    'verbosity_assertions': obj.verbosityAssertions?.value,
    'verbosity_subtests': obj.verbositySubtests?.value,
    'verbosity_test_cases': obj.verbosityTestCases?.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Sets console output style during test execution.
 *
 * @schema PytestConfigurationConsoleOutputStyle
 */
export enum PytestConfigurationConsoleOutputStyle {
  /** classic */
  CLASSIC = "classic",
  /** progress */
  PROGRESS = "progress",
  /** progress-even-when-capture-no */
  PROGRESS_HYPHEN_EVEN_HYPHEN_WHEN_HYPHEN_CAPTURE_HYPHEN_NO = "progress-even-when-capture-no",
  /** count */
  COUNT = "count",
  /** times */
  TIMES = "times",
}

/**
 * Allows to pick the action for empty parametersets in parameterization.
 *
 * @schema PytestConfigurationEmptyParameterSetMark
 */
export enum PytestConfigurationEmptyParameterSetMark {
  /** skip */
  SKIP = "skip",
  /** xfail */
  XFAIL = "xfail",
  /** fail_at_collect */
  FAIL_UNDERSCORE_AT_UNDERSCORE_COLLECT = "fail_at_collect",
}

/**
 * Configures how durations are recorded into the JUnit XML report:
 *
 * @schema PytestConfigurationJunitDurationReport
 */
export enum PytestConfigurationJunitDurationReport {
  /** total */
  TOTAL = "total",
  /** call */
  CALL = "call",
}

/**
 * Configures the format of the generated JUnit XML file.
 *
 * @schema PytestConfigurationJunitFamily
 */
export enum PytestConfigurationJunitFamily {
  /** legacy */
  LEGACY = "legacy",
  /** xunit1 */
  XUNIT1 = "xunit1",
  /** xunit2 */
  XUNIT2 = "xunit2",
}

/**
 * Configures if captured output should be written to the JUnit XML file.
 *
 * @schema PytestConfigurationJunitLogging
 */
export enum PytestConfigurationJunitLogging {
  /** no */
  NO = "no",
  /** log */
  LOG = "log",
  /** system-out */
  SYSTEM_HYPHEN_OUT = "system-out",
  /** system-err */
  SYSTEM_HYPHEN_ERR = "system-err",
  /** out-err */
  OUT_HYPHEN_ERR = "out-err",
  /** all */
  ALL = "all",
}

/**
 * Allow selective auto-indentation of multiline log messages.
 *
 * @schema PytestConfigurationLogAutoIndent
 */
export class PytestConfigurationLogAutoIndent {
  public static fromBoolean(value: boolean): PytestConfigurationLogAutoIndent {
    return new PytestConfigurationLogAutoIndent(value);
  }
  public static fromNumber(value: number): PytestConfigurationLogAutoIndent {
    return new PytestConfigurationLogAutoIndent(value);
  }
  public static fromString(value: string): PytestConfigurationLogAutoIndent {
    return new PytestConfigurationLogAutoIndent(value);
  }
  private constructor(public readonly value: boolean | number | string) {
  }
}

/**
 * A minimum log level. Can be level name or integer value.
 *
 * @schema LogLevel
 */
export enum LogLevel {
  /** CRITICAL */
  CRITICAL = "CRITICAL",
  /** ERROR */
  ERROR = "ERROR",
  /** WARNING */
  WARNING = "WARNING",
  /** INFO */
  INFO = "INFO",
  /** DEBUG */
  DEBUG = "DEBUG",
  /** NOTSET */
  NOTSET = "NOTSET",
}

/**
 * Sets the mode that the logging file is opened with. The options are 'w' to recreate the file (the default) or 'a' to append to the file.
 *
 * @schema PytestConfigurationLogFileMode
 */
export enum PytestConfigurationLogFileMode {
  /** a */
  A = "a",
  /** w */
  W = "w",
}

/**
 * Controls which directories created by the tmp_path fixture are kept around, based on test outcome.
 *
 * @schema PytestConfigurationTmpPathRetentionPolicy
 */
export enum PytestConfigurationTmpPathRetentionPolicy {
  /** all */
  ALL = "all",
  /** failed */
  FAILED = "failed",
  /** none */
  NONE = "none",
}

/**
 * Set a verbosity level specifically for assertion related output, overriding the application wide level.
 *
 * @schema PytestConfigurationVerbosityAssertions
 */
export class PytestConfigurationVerbosityAssertions {
  public static fromNumber(value: number): PytestConfigurationVerbosityAssertions {
    return new PytestConfigurationVerbosityAssertions(value);
  }
  public static fromString(value: string): PytestConfigurationVerbosityAssertions {
    return new PytestConfigurationVerbosityAssertions(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * Set the verbosity level specifically for passed subtests. A value of 1 or higher will show output for passed subtests (failed subtests are always reported). Passed subtests output can be suppressed with the value 0, which overwrites the -v command-line option.
 *
 * @schema PytestConfigurationVerbositySubtests
 */
export class PytestConfigurationVerbositySubtests {
  public static fromNumber(value: number): PytestConfigurationVerbositySubtests {
    return new PytestConfigurationVerbositySubtests(value);
  }
  public static fromString(value: string): PytestConfigurationVerbositySubtests {
    return new PytestConfigurationVerbositySubtests(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * Set a verbosity level specifically for test case execution related output, overriding the application wide level.
 *
 * @schema PytestConfigurationVerbosityTestCases
 */
export class PytestConfigurationVerbosityTestCases {
  public static fromNumber(value: number): PytestConfigurationVerbosityTestCases {
    return new PytestConfigurationVerbosityTestCases(value);
  }
  public static fromString(value: string): PytestConfigurationVerbosityTestCases {
    return new PytestConfigurationVerbosityTestCases(value);
  }
  private constructor(public readonly value: number | string) {
  }
}
