import { readFileSync } from "node:fs";
import * as path from "node:path";
import { TypeGenerator } from "json2jsii";
import type { FileBaseOptions, IResolver, Project, Task } from "../src";
import { Component, JsonPatch, TextFile } from "../src";
import { Biome, Eslint, Jest, UpgradeDependencies } from "../src/javascript";

/**
 * The name of the task (managed by `UpgradeDependencies`, see
 * `setupUpgradeDependencies`) whose workflow the `update-schemas` task is
 * wired into.
 */
const UPGRADE_BUNDLED_TASK = "upgrade-bundled";

const SCRIPT_PATH = path.join("scripts", "update-schema.js");

export interface JsiiFromJsonSchemaProps extends FileBaseOptions {
  /**
   * The name of the JSII struct (TypeScript interface) that is created.
   */
  readonly structName: string;
  /**
   * The source of the json schema.
   *
   * Can either be:
   * - A local file path. The file is read as-is at synth time.
   * - An `http(s)://` URL. The schema is vendored into `schemas/` (the file
   *   name is derived from the URL) and loaded from there at synth time.
   *   A step is added to the shared `update-schemas` task that re-downloads
   *   the file, so the vendored copy can be kept up to date automatically.
   */
  readonly schemaPath: string;
  /**
   * The path to the generated file.
   */
  readonly filePath: string;

  /**
   * The path to the generated file.
   */
  readonly transform?: (schema: any) => any;
}

/**
 * A component that generates a jsii compatible typescript file
 * from a json schema using json2jsii.
 */
export class JsiiFromJsonSchema extends TextFile {
  private readonly generator: TypeGenerator;

  constructor(project: Project, props: JsiiFromJsonSchemaProps) {
    super(project, props.filePath, {
      committed: true,
      marker: true,
      readonly: true,
    });

    const isUrl = /^https?:\/\//.test(props.schemaPath);

    // For URL sources, the schema is vendored into schemas/ and loaded from
    // there at synth time. A step is added to the shared update-schemas task
    // to periodically refresh the vendored copy from the source URL.
    const localSchemaPath = isUrl
      ? path.join("schemas", path.basename(props.schemaPath))
      : props.schemaPath;

    if (isUrl) {
      const updateSchemas = UpdateSchemasTask.getOrCreate(project);
      updateSchemas.addSchema(props.schemaPath, localSchemaPath);
    }

    // Load and parse the JSON schema file
    const schemaContent = readFileSync(localSchemaPath, "utf-8");
    const schema = JSON.parse(schemaContent);
    const transform = props.transform ?? ((s) => s);

    this.generator = TypeGenerator.forStruct(
      props.structName,
      transform(schema),
      {
        toJson: true,
        toJsonInternal: true,
        transformations: {
          convertConstToEnum: true,
          hoistSingletonUnions: true,
          convertNullUnionsToOptional: true,
          simplifyElementArrayUnions: true,
        },
      },
    );

    Eslint.of(project)?.addIgnorePattern(this.path);
    Biome.of(project)?.addFilePattern(`!${this.path}`);
    Jest.of(project)?.addIgnorePattern(this.path);
  }

  protected synthesizeContent(_: IResolver): string | undefined {
    return [
      ...(this.marker ? [`// ${this.marker}`] : []),
      this.generator.render(),
    ].join("\n");
  }
}

/**
 * A singleton component that owns the `update-schemas` task, which
 * re-downloads all URL-sourced schemas into `schemas/`. It also wires that
 * task into the `upgrade-bundled` workflow (generated by
 * `UpgradeDependencies`), during `preSynthesize`, via a `JsonPatch`. This
 * can't be done by adding a step to the `upgrade-bundled` task itself,
 * since `UpgradeDependencies` locks that task for changes once constructed.
 *
 * At most one instance may exist per project; use `getOrCreate()` rather
 * than the constructor directly.
 */
class UpdateSchemasTask extends Component {
  public static readonly TASK_NAME = "update-schemas";

  public static of(project: Project): UpdateSchemasTask | undefined {
    const isSelf = (c: Component): c is UpdateSchemasTask =>
      c instanceof UpdateSchemasTask;
    return project.components.find(isSelf);
  }

  /**
   * Returns the singleton `UpdateSchemasTask` for the project, creating it
   * if it doesn't exist yet.
   */
  public static getOrCreate(project: Project): UpdateSchemasTask {
    return (
      UpdateSchemasTask.of(project) ??
      new UpdateSchemasTask(project, UpdateSchemasTask.name)
    );
  }

  /**
   * The task that re-downloads all URL-sourced schemas into `schemas/`.
   */
  public readonly task: Task;

  private constructor(project: Project, id: string) {
    super(project, id);

    this.task = project.tasks.addTask(UpdateSchemasTask.TASK_NAME, {
      description: "Updates vendored JSON schemas from their source URL",
    });
  }

  /**
   * Adds a step that re-downloads the schema at `url` into `localPath`.
   */
  public addSchema(url: string, localPath: string) {
    this.task.exec(`node ${SCRIPT_PATH} ${url} ${localPath}`, {
      name: `update schema: ${localPath}`,
    });
  }

  public preSynthesize() {
    const project = this.project;
    const upgradeBundled = project.components.find(
      (c): c is UpgradeDependencies =>
        c instanceof UpgradeDependencies &&
        c.upgradeTask.name === UPGRADE_BUNDLED_TASK,
    );

    for (const workflow of upgradeBundled?.workflows ?? []) {
      const upgradeJob = workflow.getJob("upgrade") as any;
      if (!upgradeJob || !workflow.file) {
        continue;
      }

      const insertAt =
        upgradeJob.steps.findIndex(
          (step: any) => step.name === "Upgrade dependencies",
        ) + 1;

      workflow.file.patch(
        JsonPatch.add(`/jobs/upgrade/steps/${insertAt}`, {
          name: "Update vendored schemas",
          run: `node ./projen.js ${UpdateSchemasTask.TASK_NAME}`,
        }),
      );
    }
  }
}
