import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import * as JSONC from "comment-json";
import { GitHubActionsVersions } from "../../src/github";
import { synthSnapshot, TestProject } from "../util";

const MANIFEST_PATH = ".projen/github-actions.jsonc";

function seedManifest(
  project: TestProject,
  manifest: unknown,
  filePath: string = MANIFEST_PATH,
) {
  const absolute = join(project.outdir, filePath);
  mkdirSync(dirname(absolute), { recursive: true });
  writeFileSync(absolute, `${JSON.stringify(manifest, null, 2)}\n`);
}

function parseManifest(snapshot: Record<string, any>, path = MANIFEST_PATH) {
  expect(snapshot[path]).toBeDefined();
  // synthSnapshot already parses .jsonc files (via comment-json); round-trip
  // through JSON to strip any comment metadata for plain comparisons.
  return JSON.parse(JSON.stringify(snapshot[path]));
}

describe("GitHubActionsVersions", () => {
  test("synthesizes a manifest with the projen marker into .projen", () => {
    const project = new TestProject();
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@7", "actions/setup-node"],
    });

    const raw = synthSnapshot(project, { parseJson: false })[MANIFEST_PATH];
    expect(raw).toContain("// ~~ Generated by projen");

    const manifest = JSON.parse(
      JSON.stringify(JSONC.parse(raw, undefined, true)),
    );
    expect(manifest.actions).toEqual({
      "actions/checkout": { major: "v7", majorLocked: true },
      "actions/setup-node": {},
    });
  });

  test("normalizes major declarations and sorts actions", () => {
    const project = new TestProject();
    new GitHubActionsVersions(project.github!, {
      actions: ["zgr/action@v2", "actions/checkout@7"],
    });

    const manifest = parseManifest(synthSnapshot(project));
    expect(Object.keys(manifest.actions)).toEqual([
      "actions/checkout",
      "zgr/action",
    ]);
    expect(manifest.actions["zgr/action"].major).toBe("v2");
  });

  test("registers pinned refs with the actions provider", () => {
    const project = new TestProject();
    seedManifest(project, {
      actions: {
        "actions/checkout": {
          major: "v7",
          majorLocked: true,
          pin: "aabbcc",
          version: "v7.0.1",
        },
      },
    });
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@7", "actions/setup-node@4"],
    });

    synthSnapshot(project);

    // resolved pin wins, declared major is the fallback
    expect(project.github!.actions.get("actions/checkout@v5")).toBe(
      "actions/checkout@aabbcc",
    );
    expect(project.github!.actions.get("actions/setup-node@v4")).toBe(
      "actions/setup-node@v4",
    );
  });

  test("pins are applied to synthesized workflows", () => {
    const project = new TestProject({ stale: true });
    seedManifest(project, {
      actions: {
        "actions/stale": { major: "v11", pin: "ddeeff", version: "v11.0.0" },
      },
    });
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/stale@11"],
    });

    const snapshot = synthSnapshot(project);
    expect(snapshot[".github/workflows/stale.yml"]).toContain(
      "uses: actions/stale@ddeeff",
    );
  });

  test("preserves resolved pins from the manifest on disk", () => {
    const project = new TestProject();
    seedManifest(project, {
      actions: {
        "actions/checkout": {
          major: "v7",
          majorLocked: true,
          pin: "3d3c42e5aac5",
          version: "v7.0.1",
        },
        "actions/setup-node": { major: "v7", pin: "v7.0.0", isImmutable: true },
      },
    });
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@7", "actions/setup-node"],
    });

    const manifest = parseManifest(synthSnapshot(project));
    expect(manifest.actions).toEqual({
      "actions/checkout": {
        major: "v7",
        majorLocked: true,
        pin: "3d3c42e5aac5",
        version: "v7.0.1",
      },
      "actions/setup-node": {
        major: "v7",
        pin: "v7.0.0",
        isImmutable: true,
      },
    });
  });

  test("changing the declared major drops the stale pin", () => {
    const project = new TestProject();
    seedManifest(project, {
      actions: {
        "actions/checkout": {
          major: "v7",
          majorLocked: true,
          pin: "3d3c42e5aac5",
          version: "v7.0.1",
        },
      },
    });
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@8"],
    });

    const manifest = parseManifest(synthSnapshot(project));
    expect(manifest.actions["actions/checkout"]).toEqual({
      major: "v8",
      majorLocked: true,
    });
  });

  test("actions removed from the projenrc are dropped from the manifest", () => {
    const project = new TestProject();
    seedManifest(project, {
      actions: {
        "actions/checkout": { major: "v7", pin: "aabbcc" },
        "actions/setup-go": { major: "v5", pin: "ddeeff" },
      },
    });
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout"],
    });

    const manifest = parseManifest(synthSnapshot(project));
    expect(Object.keys(manifest.actions)).toEqual(["actions/checkout"]);
  });

  test("creates the update task with configuration args", () => {
    const project = new TestProject();
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@7"],
      immutablePins: false,
      upgradeMajorVersions: true,
      reportMajorVersions: true,
      cooldownDays: 14,
    });

    const tasks = synthSnapshot(project)[".projen/tasks.json"].tasks;
    const update = tasks["update-github-actions"];
    expect(update.steps[0]).toEqual({
      builtin: "github/update-github-actions",
      args: [
        MANIFEST_PATH,
        "--cooldown-days=14",
        "--mutable-pins",
        "--upgrade-major-versions",
        "--report-major-versions",
      ],
      receiveArgs: true,
    });
  });

  test("update task defaults and re-synth spawn", () => {
    const project = new TestProject();
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@7"],
    });

    const tasks = synthSnapshot(project)[".projen/tasks.json"].tasks;
    const update = tasks["update-github-actions"];
    expect(update.steps[0].args).toEqual([MANIFEST_PATH, "--cooldown-days=7"]);
    expect(update.steps[1]).toEqual({
      spawn: project.defaultTask!.name,
    });
  });

  test("supports a custom manifest path", () => {
    const project = new TestProject();
    new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@7"],
      jsonPath: "config/actions.jsonc",
    });

    const snapshot = synthSnapshot(project);
    expect(snapshot["config/actions.jsonc"]).toBeDefined();
    const tasks = snapshot[".projen/tasks.json"].tasks;
    expect(tasks["update-github-actions"].steps[0].args[0]).toBe(
      "config/actions.jsonc",
    );
  });

  test("throws on invalid action specs", () => {
    const project = new TestProject();
    const versions = new GitHubActionsVersions(project.github!);

    expect(() => versions.addAction("not-an-action")).toThrow(
      /expected "owner\/repo"/,
    );
    expect(() => versions.addAction("actions/checkout@v7.0.1")).toThrow(
      /only major version lines may be declared/,
    );
  });

  test("throws on conflicting duplicate declarations", () => {
    const project = new TestProject();
    const versions = new GitHubActionsVersions(project.github!, {
      actions: ["actions/checkout@7"],
    });

    expect(() => versions.addAction("actions/checkout@8")).toThrow(
      /already declared/,
    );
    // identical re-declaration is fine
    versions.addAction("actions/checkout@7");
  });

  test("supports actions in subdirectories", () => {
    const project = new TestProject();
    new GitHubActionsVersions(project.github!, {
      actions: ["github/codeql-action/init@3"],
    });

    const manifest = parseManifest(synthSnapshot(project));
    expect(manifest.actions["github/codeql-action/init"]).toEqual({
      major: "v3",
      majorLocked: true,
    });
  });
});
