#!/bin/bash
set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/integ-common.sh"

REPO_ROOT=$(get_repo_root)
TARBALL=$(find_npm_tarball "$REPO_ROOT")

setup_workdir
setup_npm_projen "$TARBALL"

# Create a new TypeScript project
echo "=== Create a TypeScript project ==="
npx projen new typescript --project-tree --package-manager=npm --projen-version="$TARBALL"

# Eject projen from the project. This removes projen from the project's
# configuration and drops in scripts/run-task.cjs (the bundled task runner).
echo "=== Eject ==="
npx projen eject

echo "=== Verify eject artifacts ==="
# The bundled task runner must have been generated.
if [ ! -f scripts/run-task.cjs ]; then
  echo "ERROR: scripts/run-task.cjs was not generated by eject" >&2
  exit 1
fi
# projen must no longer be referenced by the project.
if grep -q '"projen"' package.json; then
  echo "ERROR: projen is still referenced in package.json after eject" >&2
  exit 1
fi
# The package scripts must be rewired to the bundled runner.
if ! grep -q 'scripts/run-task.cjs' package.json; then
  echo "ERROR: package.json scripts were not rewired to scripts/run-task.cjs" >&2
  exit 1
fi

# Simulate a repository where projen is no longer installed at all, so we know
# the bundled runner is genuinely self-contained.
echo "=== Remove projen from node_modules ==="
rm -rf node_modules/projen node_modules/.bin/projen

# Running a task must now work entirely through scripts/run-task.cjs, without
# projen on the path. This is the core guarantee of "projen eject" and guards
# the regressions behind issues #3679 and #4407.
echo "=== Run 'compile' through the ejected runner ==="
npm run compile

if [ ! -f lib/index.js ]; then
  echo "ERROR: running 'compile' through scripts/run-task.cjs did not produce lib/index.js" >&2
  exit 1
fi

echo "Eject integration test passed!"
