export const PROJEN_RC = '.projenrc.js';
export const PROJEN_MARKER = '~~ Generated by ' + 'projen'; // we split into two so /this/ file does not match the marker
export const GENERATION_DISCLAIMER = `${PROJEN_MARKER}. To modify, edit ${PROJEN_RC} and run "npx projen".`;

// eslint-disable-next-line @typescript-eslint/no-require-imports
export const PROJEN_VERSION = require('../version.json').version;
