export const PROJEN_RC = '.projenrc.js';
export const PROJEN_DIR = '.projen';
export const PROJEN_MARKER = '~~ Generated by ' + 'projen'; // we split into two so /this/ file does not match the marker

// eslint-disable-next-line @typescript-eslint/no-require-imports
export const PROJEN_VERSION = require('../package.json').version;
